# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-06 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('l1', models.CharField(blank=True, max_length=500, null=True)),
                ('l2', models.CharField(blank=True, max_length=500, null=True)),
                ('l3', models.CharField(blank=True, max_length=500, null=True)),
                ('p', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
