# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-10 11:52
from __future__ import unicode_literals

import New_Home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('fee', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('short_des', models.CharField(blank=True, max_length=1000, null=True)),
                ('long_des', models.CharField(blank=True, max_length=2000, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('skill', models.CharField(blank=True, max_length=200, null=True)),
                ('students', models.CharField(blank=True, max_length=200, null=True)),
                ('classes', models.CharField(blank=True, max_length=200, null=True)),
                ('l1', models.CharField(blank=True, max_length=200, null=True)),
                ('l2', models.CharField(blank=True, max_length=200, null=True)),
                ('l3', models.CharField(blank=True, max_length=200, null=True)),
                ('l4', models.CharField(blank=True, max_length=200, null=True)),
                ('l5', models.CharField(blank=True, max_length=200, null=True)),
                ('l6', models.CharField(blank=True, max_length=200, null=True)),
                ('l7', models.CharField(blank=True, max_length=200, null=True)),
                ('l8', models.CharField(blank=True, max_length=200, null=True)),
                ('l9', models.CharField(blank=True, max_length=200, null=True)),
                ('l10', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='New_Home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('des', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=New_Home.models.Trainer, null=New_Home.models.Trainer, on_delete=django.db.models.deletion.CASCADE, to='New_Home.Course')),
                ('trainer', models.ForeignKey(blank=New_Home.models.Trainer, null=New_Home.models.Trainer, on_delete=django.db.models.deletion.CASCADE, to='New_Home.Trainer')),
            ],
        ),
        migrations.AddField(
            model_name='sub_title',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='New_Home.Title'),
        ),
        migrations.AddField(
            model_name='course',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='New_Home.Courses_Category'),
        ),
    ]
