# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-10 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0002_auto_20190710_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_category',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
