# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-11 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0004_auto_20190711_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
