# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0005_auto_20190711_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Main', to='New_Home.Trainer'),
        ),
        migrations.AddField(
            model_name='course',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Secondary', to='New_Home.Trainer'),
        ),
    ]
