# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-11 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0006_auto_20190711_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
