# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0007_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seo_des',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_keys',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
