# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-11 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0010_title_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cat2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat2', to='New_Home.Courses_Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='New_Home.Courses_Category'),
        ),
    ]
