# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0011_auto_20190711_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='des',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
