# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('New_Home', '0012_auto_20190711_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.CharField(blank=True, max_length=100, null=True)),
                ('ps', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('call', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('map', models.CharField(blank=True, max_length=2000, null=True)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('skill', models.CharField(blank=True, max_length=200, null=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('short_des', models.CharField(blank=True, max_length=1000, null=True)),
                ('long_des', models.CharField(blank=True, max_length=2000, null=True)),
                ('seo_des', models.CharField(blank=True, max_length=2000, null=True)),
                ('seo_keys', models.CharField(blank=True, max_length=2000, null=True)),
                ('l1', models.CharField(blank=True, max_length=200, null=True)),
                ('l2', models.CharField(blank=True, max_length=200, null=True)),
                ('l3', models.CharField(blank=True, max_length=200, null=True)),
                ('l4', models.CharField(blank=True, max_length=200, null=True)),
                ('l5', models.CharField(blank=True, max_length=200, null=True)),
                ('l6', models.CharField(blank=True, max_length=200, null=True)),
                ('l7', models.CharField(blank=True, max_length=200, null=True)),
                ('l8', models.CharField(blank=True, max_length=200, null=True)),
                ('l9', models.CharField(blank=True, max_length=200, null=True)),
                ('l10', models.CharField(blank=True, max_length=200, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='New_Home.Event_Category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
