# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0013_event_category_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_category',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
