# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0014_event_category_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
    ]
