# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0016_auto_20190712_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='c_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
