# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0020_auto_20190712_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='user',
            new_name='usr',
        ),
    ]
