# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0021_auto_20190712_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
