# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0022_auto_20190712_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
