# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0023_events_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='students',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
