# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New_Home', '0024_events_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, max_length=200, null=True)),
                ('end_date', models.DateField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start_date',
        ),
        migrations.AddField(
            model_name='dates',
            name='Event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='New_Home.Events'),
        ),
    ]
