# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170920_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
